[package]
name = "bom_receipt"
type = "lib"
authors = ["American Accounting Company"]

[dependencies]
pacioli = { path = "../pacioli" }
hash = { path = "../hash" }
event_harness = { path = "../event-harness" }
