[workspace]
members = ["pacioli", "hash", "ledger", "receipt", "event-harness", "rulebook", "event-complete", "bom-receipt", "event-bom-receipt", "repo", "event-repo-open", "event-repo-close", "novate", "event-novate", "ust-trade", "event-ust", "transition", "nullify"]
default-member = "transition"
