[package]
name = "event_harness"
type = "lib"
authors = ["American Accounting Company"]

[dependencies]
pacioli = { path = "../pacioli" }
ledger = { path = "../ledger" }
receipt = { path = "../receipt" }
