[package]
name = "event_complete"
type = "bin"
authors = ["American Accounting Company"]
[dependencies]
rulebook = { path = "../rulebook" }
receipt = { path = "../receipt" }
ledger = { path = "../ledger" }
event_harness = { path = "../event-harness" }
